// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtS2YlfErQxOJqtSAxiZZKS5T4jUreIWo',
    appId: '1:379004474275:web:2cbd615af1b2669a4e8016',
    messagingSenderId: '379004474275',
    projectId: 'khadamatii-a910a',
    authDomain: 'khadamatii-a910a.firebaseapp.com',
    storageBucket: 'khadamatii-a910a.firebasestorage.app',
    measurementId: 'G-31GRHE87G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Ldwx0UlA38Xa8JnCfPTrpX7LS6BLXhI',
    appId: '1:379004474275:android:e7499133930d7cb74e8016',
    messagingSenderId: '379004474275',
    projectId: 'khadamatii-a910a',
    storageBucket: 'khadamatii-a910a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgA1emBIqm1oAJkWH_G6buHt_m7TGvJa8',
    appId: '1:379004474275:ios:b62dd5210ed14bd54e8016',
    messagingSenderId: '379004474275',
    projectId: 'khadamatii-a910a',
    storageBucket: 'khadamatii-a910a.firebasestorage.app',
    iosBundleId: 'com.example.projectaladimi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgA1emBIqm1oAJkWH_G6buHt_m7TGvJa8',
    appId: '1:379004474275:ios:b62dd5210ed14bd54e8016',
    messagingSenderId: '379004474275',
    projectId: 'khadamatii-a910a',
    storageBucket: 'khadamatii-a910a.firebasestorage.app',
    iosBundleId: 'com.example.projectaladimi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtS2YlfErQxOJqtSAxiZZKS5T4jUreIWo',
    appId: '1:379004474275:web:4ce8cb1cebf3da9b4e8016',
    messagingSenderId: '379004474275',
    projectId: 'khadamatii-a910a',
    authDomain: 'khadamatii-a910a.firebaseapp.com',
    storageBucket: 'khadamatii-a910a.firebasestorage.app',
    measurementId: 'G-8FFFENJH31',
  );

}